functions:
  flexGraphql:
    name: ${env:PROJECT_SLUG}-${sls:stage}-${self:service}
    handler: flexGraphql.handler
    timeout: 30
    provisionedConcurrency: 1
    memorySize: 5000 # Overwrite the default memory size. Default is 1024..
    reservedConcurrency: 200
    events:
      - http:
          path: /graphql
          method: POST
          private: false
